---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4724861842-la1I4Qa3XPhq99C7X1Q2ek2MN35apCjfEIee7T7
:access_token_secret: dBYUdXc3Ux5W9teGXV3ZABvuMxm4l2bpE5v7FIEdqymnz
